### ISSUE TITLE
Error in Env.lua

### ISSUE THREAD

**Issue by htordeux** [kirk24788/KPS#1]
Kirk,

I've tried your KPS, but unfortunately, got an error in env.lua, unable to solve it myself, if you want I'll test it again and send you the error message

**Comment by kirk24788** [comment]
Yes - please send the error message. If the error goes away after an ui reload - I'm working on it...if not then there's probably an error in one of those rotations...

**Comment by htordeux** [comment]
I've changed the toc and an unknown spell in DK
the error message is :

Message: Interface\AddOns\KPS\env.lua:85: attempt to index upvalue 'classEnvs' (a nil value)
Time: Fri Jul  3 11:05:00 2015
Count: 1
Stack: Interface\AddOns\KPS\env.lua:85: in function <Interface\AddOns\KPS\env.lua:84>

**Comment by kirk24788** [comment]
OK - got this fixed....was only affecting DK's - the rotations still ain't that good....SimC does strange - but at least this issue is fixed.
