### ISSUE TITLE
spells.inRange is missing

### ISSUE THREAD

**Issue by pcmdgit** [kirk24788/KPS#10]
can't find any function for this as documented in Readme.md

**Comment by kirk24788** [comment]
The documentation is generated from the comments - the function is at the end of `modules/spell/spell_range.lua`.

Currently used in `modules/spell/spell_state.lua` in the function `Spell.canBeCastAt`.

**Comment by pcmdgit** [comment]
oh sorry didnt saw that :S

the following didnt worked for me:


 {spells.defile, 'player.hasTalent(7, 2) and spells.defile.inRange("target")'}, -- defile


could also because of player.hasTalent.

GetTalentRowSelectionInfo returns isFree and talentID

talentid is for GetTalentInfo

**Comment by kirk24788** [comment]
Did you get a rotation error or did it just not work?
I'll take a look at it once I'm home - maybe it is because defile extends blood boil or because the AoE spells have invalid `IsSpellInRange`return values...
