### ISSUE TITLE
player.hasTalent(<ROW>,<TALENT>) breaks rotations

### ISSUE THREAD

**Issue by rayfish** [kirk24788/KPS#15]
KPS won't load rotations with for example `player.hasTalent(7,1)` as a condition in them. 
I can't provide further debugging information but this was broken by 7.0.3.

I'm curious what the state of development is. Should KPS now be generally be working in 7.0.3 or are there still known issues that will be fixed in the near future?

I am experiencing quite a few other issues while working on various 7.0.3 rotations (for example `kps.heal.defaultTank.hpIncoming` or `.lastCasted(duration)` throwing lua errors) but I'm not sure if it makes sense to open issues for all of them when they are known issues and @kirk24788 is backed up with other work.

**Comment by kirk24788** [comment]
If you encounter problems, just create a ticket for it, helps me a lot to find things not working with 7.0.3 - I'm currently working on the rotations but if there are any issues just create tickets for them...I'll look into them as soon as I can

**Comment by kirk24788** [comment]
Btw. when you create tickets for hpIncoming and .lastCaster - could you also mention classes/specs?

I tried to reproduce this, but I don't get any lua errors
