### ISSUE TITLE
<SPELL>.lastCasted(<DURATION>) error

### ISSUE THREAD

**Issue by rayfish** [kirk24788/KPS#17]
`events.lua:163 - Error Interface\AddOns\KPS\core\parser.lua:639: attempt to index a nil value on OnUpdate function function: 0x1c6276880`

when using `and not spell.lifebloom.lastCasted(6)` in a rotation

**Comment by kirk24788** [comment]
It should be `and not spells.lifebloom.lastCasted(6)`, I'll extend the documentation to make this clearer by giving a few examples.

**Comment by rayfish** [comment]
Thank you, that fixed the problem. I copy-pasted from the example in the readme and the "s"  was also missing there.
