### ISSUE TITLE
healing targeting problems

### ISSUE THREAD

**Issue by rayfish** [kirk24788/KPS#19]
- I absolutely can't get the druid rotation in my fork to heal anything but itself. It seems to evaluate conditions correctly but always ends up healing itself. I've spent 2 hours attempting to debug this but I haven't even figured out how to print either of these variable's values to the console.
My suspicion is that `kps.heal.defaultTank` and `kps.heal.defaultTank` seem to be "player" all the time for some reason.

- `tanksInRaid()` doesn't work as well as it used to because most buffs (righteous fury, blood presence) to detect tanks are gone in 7.0.3.
It would be good to have it return "focus" if no players with the "tank" role are found and "focus" is healable. That's also what JPS did.

**Comment by kirk24788** [comment]
Sorry, I don't have much time currently, I'll try out your rotation this evening - I've spent most of the time I had with DPS rotations.

Regarding `tanksInRaid ` - `UnitGroupRolesAssigned` should suffice, or am I wrong? I'll think about the focus fallback, just give me some time to test this.

The `defaultTarget`/`defaultTank` should still default to focus or target if those are low enough...I'll have to test this...

You also mentioned in another issue that range should be checked - this is actually done for most targets but the tanks - I'll fix that.

**Comment by rayfish** [comment]
No problem, I know you are very busy! 
I'm just trying to replicate what I had working before with JPS now that its development seems to have come to an end. 
Back then I could use the profile as an autopilot for healing while not having to pay total attention to the game.

Yes, UnitGroupRolesAssigned should suffice unless you are using the profile outside raids like I do. (BGs, questing with friends, Ashran and so on). Being able to quickly set focus to manually set the tank worked great as a fallback in JPS. 
Of course you are probably right in that`defaultTarget/defaultTank` should do this anyway, I didn't think of that because it always seemed to target itself.

Thank you for looking into the rotation. 😃 
Note that for example Germination (and a handful of other spells) have different Spell IDs in-game than what is generated from wowhead into `druid_spells.lua`. I think this is wowhead's fault. Just so you don't wonder why the rotation doesn't work "out of the box".

http://www.wowhead.com/spell=155675/germination (old)
http://www.wowhead.com/spell=155777/rejuvenation-germination (new)
