### ISSUE TITLE
jps.findMeAggroTank port

### ISSUE THREAD

**Issue by rayfish** [kirk24788/KPS#20]
A new `"heal.aggroTank" `function based on `jps.findMeAggroTank(targetUnit)` would be very, very useful for instance and raid healing to find a tank to keep HoTs like Lifebloom on. 
I tried to "port" it from jps myself and failed miserably.

**Comment by kirk24788** [comment]
I've added the function - but I'm on vacation currently - so I can't test if it actually works...I'll test it next friday when I'm back.

**Comment by rayfish** [comment]
thank you very much for fixing this. healing and aggroTank works perfect now.
