### ISSUE TITLE
kirk, non issue question

### ISSUE THREAD

**Issue by jamisonla** [kirk24788/KPS#24]
If this is inappropriate you may just delete this post and ignore but, I once said that I would donate $ for the continuation of JPS or your KPS and I would make good on that commitment if you like. I am also interested in finding a lua unlocker for MAC if you know of anything.

**Comment by kirk24788** [comment]
Sorry, I've been rather busy and haven't updated KPS in a while, although I'm still using it...
Regarding the unlocker - please contact be at mario@mancino-net.de
