### ISSUE TITLE
Unsupported Talents

### ISSUE THREAD

**Issue by jamisonla** [kirk24788/KPS#27]
Is there a way to turn off the Unsupported Talents message? I favor talents that seem to be unsupported and it fills up my chat

**Comment by kirk24788** [comment]
Currently no although those messages actually make sense, as the rotations will most likely not work with them (At least not fully).
You could just remove those warnings, by editing the corresponding rotation and changing the last line:
`,"Icy Veins", {-1,-3,0,-3,0,-2,1})`
to
`,"Icy Veins")`
The last array is responsible for those checks, every talent tier has it's own number:
`1 to 3` - only accept talent `n`
`-1 to -3`- accept all talents but `n`
`0` - accept all talents

I'll increase the delay between those notification messages, or maybe only show them once per fight.

**Comment by jamisonla** [comment]
It still works. I am replacing them with passives. I will try the editing tonight.

Thanks!
Jamison Arnholt



Sent from my iPhone

On Jan 11, 2017, at 4:05 AM, kirk24788 <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently no although those messages actually make sense, as the rotations will most likely not work with them (At least not fully).
You could just remove those warnings, by editing the corresponding rotation and changing the last line:
,"Icy Veins", {-1,-3,0,-3,0,-2,1})
to
,"Icy Veins")
The last array is responsible for those checks, every talent tier has it's own number:
1 to 3 - only accept talent n
-1 to -3- accept all talents but n
0 - accept all talents

I'll increase the delay between those notification messages, or maybe only show them once per fight.

-
