### ISSUE TITLE
Healing Issue with dead players

### ISSUE THREAD

**Issue by tbhozie** [kirk24788/KPS#28]
So I have a pretty basic healing setup for my resto shaman and everything seems to work perfect, except for when someone dies in the raid/group. 

Here is just the basic setup - 

    {spells.riptide, 'heal.defaultTarget.hp<0.95 and not player.hasBuff(spells.tidalWaves)', kps.heal.defaultTarget},
    {spells.healingSurge, 'heal.defaultTarget.hp<0.4', kps.heal.defaultTarget},
    {spells.chainHeal, 'kps.multiTarget and heal.averageHpIncoming < 0.85 and heal.defaultTarget.hp < 1', kps.heal.defaultTarget},
    {spells.healingWave, 'heal.defaultTarget.hp<0.90', kps.heal.defaultTarget},

It works great on just getting the lowest member in the group, but if someone dies it seems to act weird I think as if it is thinking they are the lowest. I tried adding `not heal.defaultTarget.isDead` but that did not work

**Comment by kirk24788** [comment]
Hmm....`isDead` was broken, they changed the return value of `UnitIsDeadOrGhost`...but I'll also change the defaultTarget and defaultTank to make sure they don't return dead players
