### ISSUE TITLE
Hunter Marks Vulnerable

### ISSUE THREAD

**Issue by Holliday00** [kirk24788/KPS#29]
Anyone.

I've amended Silk_sn's Marks rotation for a Trick Shot build that works quite well, but it does not refresh the Vulnerable debuff if there is another Marks hunter applying Vulnerable on the target. Is there a way to make it so it only recognizes your own debuff? 

Also in the multitarget portion of the rotation it casts multi-shot consecutively if Marking Targets keeps procing. Can anyone help with this as well?

If you would like me to post the rotation that I have, you will have to explain to me how to do this as I am very ignorant. I can copy and paste it but it gets messy.

**Comment by kirk24788** [comment]
Yeh, I really need to the the rotation for this ;)
Please paste it, and either enclose it manually with backticks (\`)
Or pastet in, select it and click on the 'Insert code' Button in the comment editor ('<>').

**Comment by Holliday00** [comment]
[hunter_marksmanship.zip](https://github.com/kirk24788/KPS/files/751868/hunter_marksmanship.zip)

does this zip work?

**Comment by kirk24788** [comment]
Well, I corrected the rotation to no longer use `kps.Spell.fromId(xxx)` this is bad style and should be avoided, as all spells should already exist in the `hunter_spells.lua` file.

Regarding your first issue:
```
    {spells.markedShot, 'not target.hasDebuff(kps.Spell.fromId(187131) or target.myDebuffDuration(kps.Spell.fromId(187131)) < 2)'},
```
should be:
```
    {spells.markedShot, 'not target.hasMyDebuff(spells.vulnerable or target.myDebuffDuration(spells.vulnerable) < 2)'},
```
or better:
```
    {spells.markedShot, 'not target.hasMyDebuff(spells.vulnerable or target.myDebuffDuration(spells.vulnerable) < 2)'},
```

**Comment by kirk24788** [comment]
Regarding your multishot issue:
```
   {spells.multishot, 'player.hasBuff(kps.Spell.fromId(223138))'},
```
should be:
```
   {spells.multishot, 'player.hasBuff(spells.markingTargets)'},
```
if you want to avoid recasting it within N seconds, write:
```
   {spells.multishot, 'player.hasBuff(spells.markingTargets) and not spells.multishot.lastCasted(N)'},
```
