### ISSUE TITLE
isCastingSpell

### ISSUE THREAD

**Issue by brainmr** [kirk24788/KPS#34]
Hey Kirk,

@function `<UNIT>.isCastingSpell(<SPELL>)` - returns true if the unit is casting (or channeling) the given <SPELL> (i.e. `target.isCastingSpell(spells.immolate)`)

Trying to use this to check for player channeling a spell but getting an error, UnitCastingInfo needs "unit". 

Tried to modify the (k) there but didnt get it to work. It should work for casts and channels too right?

_local name, _, _, _, startTime, endTime, _, interrupt = UnitCastingInfo(k)_

Cheers

**Comment by htordeux** [comment]
now working correctly in new update

**Comment by kirk24788** [comment]
Closing this - if this still persists please re-open
