### ISSUE TITLE
latest updates

### ISSUE THREAD

**Issue by blackcardi** [kirk24788/KPS#44]
the latest updates causes huge UI issues upon loggin in. I think it may be caused by the incoming damage changes as it triggers the red flashing low health effect. 

To rule other things out I deleted the WTF folder and loaded kps with stock UI and It still did it.

**Comment by htordeux** [comment]
same for me i delete the _wow.lua in toc file and it was fine

**Comment by blackcardi** [comment]
Ok I will try that.

On Apr 18, 2017, at 12:52 PM, htordeux <notifications@github.com<mailto:notifications@github.com>> wrote:


same for me i delete the _wow.lua in toc file and it was fine

**Comment by kirk24788** [comment]
The toc file is generated, and the _wow.lua shouldn't be part of it.
The TOC is based on the _test.lua require statements, but only statements without leading whitespaces are used, unfortunately the leading whitespace have been removed by commit 05b56640a33d0b4b0330c17dbac0cc014246e664
causing this.
