### ISSUE TITLE
Incoming damage error Blood

### ISSUE THREAD

**Issue by blackcardi** [kirk24788/KPS#45]
parser.lua:84 - Rotation-Error: Your rotation has an error in condition: 'kps.incomingDamage(5) > player.hpMax * 0.1 or player.runicPower >= 70':
   :651: attempt to call a nil value

I get this error now on death strike on the blood rotation where it used to work fine. I have no idea how the incoming damage works and had a _friend write that condition for me_ (this is untrue he said it was stock, he just gave me his changed rotation). Can it be fixed?

**Comment by kirk24788** [comment]
Well - it was stock, but `kps.incomingDamage(*)` was removed. It has been replaced by `player.incomingDamage` - which is slightly different. The old function only worked on the player, but gave you the ability to determine the time - the new function works on all targets, but always reports the the amount of damage within the last 4 seconds.

While this hasn't been changed in the stock rotation, you might also change the condition slightly to:
```player.incomingDamage > player.hpMax * 0.125 or ...```
to compensate for the changed time window.
