### ISSUE TITLE
activeEnemies()

### ISSUE THREAD

**Issue by alxaw** [kirk24788/KPS#7]
http://i.imgur.com/PFsXBLb.png

parser.lua:57 - Rotation-Error: Your rotation has an error in condition: 'activeEnemies() => 3':
:211 bad argument #1 to 'unpack' (table expected, got nil)

**Comment by htordeux** [comment]
I think the kps.env.activeEnemies is not completely wriiten
I had the same error, either you change it to kps.multitarget

or add in modules/unlock/basic a piece of code and change activeEnemies() to activeEnemies.count

kps.activeEnemies = {}
kps.activeEnemies.prototype = {}
kps.activeEnemies.metatable = {}

function kps.activeEnemies.prototype.count(self)
    if kps.multiTarget then
        return 6
    else
        return 1
    end
end

function kps.activeEnemies.new()
    local inst = {}
    setmetatable(inst, kps.activeEnemies.metatable)
    return inst
end

kps.activeEnemies.metatable.__index = function (table, key)
    local fn = kps.activeEnemies.prototype[key]
    if fn == nil then
        error("Unknown Keys-Property '" .. activeEnemies .. "'!")
    end
    return fn(table)
end
